### ISSUE TITLE
Option to ignore untrusted certificates

### ISSUE THREAD

**Issue by Wysselbie** [FriendsOfShopware/shopware-cli#108]
### Please describe the feature you would like to see implemented.

In my setup I use [devenv](https://devenv.sh/) with [Caddy](https://caddyserver.com/).
The problem I encountered is that Caddy can't install it's certificate due to permission issues inside `devenv up` (can't run `sudo` in non-interactive shell).

This results in the following error if I use `shopware-cli project admin-api`:
```
FATA[0000] Post "https://127.0.0.1:8000/api/oauth/token": x509: “Caddy Local Authority - ECC Intermediate” certificate is not trusted
```

It would be nice to have a flag/option to ignore this behavior.

**Comment by shyim** [comment]
that command should support already `--insecure`

**Comment by shyim** [comment]
You can configure it in the yaml config

```
url: http://localhost:8000
admin_api:
    username: admin
    password: shopware
    disable_ssl_check: true
```
