### ISSUE TITLE
NPM executable file not found in $PATH

### ISSUE THREAD

**Issue by element-code** [FriendsOfShopware/shopware-cli#132]
### PHP Version

8.1

### Shopware Version

6.4.20

### Actual behaviour

Running `package` in our GitLab CI with Docker.
Package fails with `building assets: exec: \"npm\": executable file not found in $PATH`

```
Executing "step_script" stage of the job script 00:09
Using docker image sha256:45cbf57a5c858edc1d07d38fb50d4efe17ba532584a20769ea3c7c713ef7f664 for ghcr.io/friendsofshopware/shopware-cli:v0.1-phpv8.1 with digest ghcr.io/friendsofshopware/shopware-cli@sha256:7c29a5043e58e3aa7e56bf2543b6f4264238da4df3020710a67db84702f03bc0 ...
$ shopware-cli --version
shopware-cli version 0.1.54
$ shopware-cli extension zip ./ package --release --verbose
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file
Nothing to install, update or remove
Generating optimized autoload files
Cloning into '/tmp/extension2478198386'...
Updating files: 100% (17171/17171), done.
Usage:
  shopware-cli extension zip [path] [branch] [flags]
Flags:
      --disable-git   Use the source folder as it is
  -h, --help          help for zip
      --release       Release mode (remove app secrets)
Global Flags:
      --config string   config file (default is $HOME/.shopware-cli.yaml)
      --verbose         show debug output
time="2023-03-08T14:50:21Z" level=fatal msg="building assets: exec: \"npm\": executable file not found in $PATH"
```

### Expected behaviour

The docker image would provide the required npm

### Steps to Reproduce?

gitlab-ci.yml
```yml
build:package:
  image:
    name: ghcr.io/friendsofshopware/shopware-cli:v0.1-phpv8.1
    entrypoint: [""]
  tags:
    - docker
  variables:
    FILE_NAME: $BASE_FILE_NAME.zip
    EXT_INTERNAL_NAME_PATTERN: -package.zip
  artifacts:
    name: $BASE_FILE_NAME
    paths:
      - "*"
  stage: build
  script:
    - shopware-cli --version
      #package the extension (executes prepare, build & zip)
    - shopware-cli extension zip ./ package --release --verbose
```
