### ISSUE TITLE
unzip: command not found

### ISSUE THREAD

**Issue by element-code** [FriendsOfShopware/shopware-cli#136]
### Question

After packaging the extension, we unpack the zip to remove some files and then expose the extension main folder as artifact to GitLab.
This doesn't work anymore, since unzip is no longer available (entry point was `/bin/sh -c` before).

```
$ shopware-cli --version
shopware-cli version 0.1.54
[...]
$ unzip $EXT_INTERNAL_NAME-package.zip
/bin/bash: line 131: unzip: command not found
```

1. is there a way to get unzip back working?
2. is there a better way of doing this?

```yml
build:package:
  image:
    name: ghcr.io/friendsofshopware/shopware-cli:v0.1-phpv8.1
    entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
  tags:
    - docker
  variables:
    FILE_NAME: $BASE_FILE_NAME.zip
    EXT_INTERNAL_NAME_PATTERN: -package.zip
  artifacts:
    name: $BASE_FILE_NAME
    paths:
      - "*"
  stage: build
  script:
    - shopware-cli --version

      #package the extension (executes prepare, build & zip)
    - shopware-cli extension zip ./ package --disable-git --release --verbose

      #fetch the internal name from the zip name (the technical name from the extension composer.json)
    - EXT_INTERNAL_NAME=$(ls | grep -e "$EXT_INTERNAL_NAME_PATTERN" | head -1)
    - EXT_INTERNAL_NAME=${EXT_INTERNAL_NAME/$EXT_INTERNAL_NAME_PATTERN/}

      #unzip the package, we need the raw files for our artifact
    - unzip $EXT_INTERNAL_NAME-package.zip

      # remove everything we don't want in our artifact
    - find . -not -name $EXT_INTERNAL_NAME -maxdepth 1 -exec rm -r {} \;
```
