### ISSUE TITLE
Error when building plugin administration files

### ISSUE THREAD

**Issue by LiaraAlis** [FriendsOfShopware/shopware-cli#170]
### Actual behaviour

Using the following `.gitlab-ci.yml`:
```yml
stages:
    - test
    - build
    - deploy

build:
    stage: build
    when: always
    only:
        - tags
        - web
    image:
        name: ghcr.io/friendsofshopware/shopware-cli:latest
        entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
    tags:
        - docker
    variables:
        GIT_DEPTH: "0"
    script:
        - shopware-cli extension zip .
    artifacts:
        name: SheTinyMce
        paths:
            - SheTinyMce-*.zip

validate_plugin:
    stage: test
    when: always
    only:
        - tags
        - web
    image:
        name: ghcr.io/friendsofshopware/shopware-cli:latest
        entrypoint: [ "" ]
    tags:
        - docker
    variables:
        GIT_DEPTH: "0"
    script:
        - shopware-cli extension validate .

upload_to_store:
    stage: deploy
    dependencies:
        - build
    when: manual
    image:
        name: ghcr.io/friendsofshopware/shopware-cli:latest
        entrypoint: [ "" ]
    tags:
        - docker
    variables:
        GIT_DEPTH: "0"
    script:
        - shopware-cli account producer extension upload SheTinyMce-*.zip
        - shopware-cli account producer extension info push .
```

Building plugin results in the following error message.
```
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/tmp/extension15723358[90](https://git.blackpoint.de/shopware/SheTinyMce/-/jobs/2734#L90)/src/Administration/Resources/app/administration/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/extension1572335890/src/Administration/Resources/app/administration/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/extension1572335890/src/Administration/Resources/app/administration/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/extension1572335890/src/Administration/Resources/app/administration/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/extension1572335890/src/Administration/Resources/app/administration/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/extension1572335890/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/extension1572335890/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/tmp/extension1572335890/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /tmp/extension1572335890/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/tmp/extension1572335890/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /tmp/extension1572335890/src/Administration/Resources/app/administration/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

Furthermore, the following message appears: `@Deprecated: You are using an incompatible Node.js version. Supported version range: ^16.0.0`

Used `package.json` for administration:
```json
{
  "dependencies": {
    "@tinymce/tinymce-vue": "^3.2.8"
  }
}
```

### Expected behaviour

Plugin can be created successfully.

### Steps to Reproduce?

Building plugin as described above.
