### ISSUE TITLE
config pull multiple email templates

### ISSUE THREAD

**Issue by wrongspot** [FriendsOfShopware/shopware-cli#287]
### PHP Version

8.1

### Shopware Version

6.4.20.2

### Plugin Version

0.4.5

### Actual behaviour

If there are several email templates for the same type, the export is always saved to the same file path

```yaml
mail_template:
  - id: 554b74d5e6e940ac94728f6aafc99112
    translations:
      - language: English
        sender_name: '{{ salesChannel.name }}'
        subject: Contact form received - {{ salesChannel.name }}
        html: .shopware-cli/mail-template/contact_form/English-html.twig
        plain: .shopware-cli/mail-template/contact_form/English-plain.twig
        custom_fields: null
      - language: Deutsch
        sender_name: '{{ salesChannel.name }}'
        subject: Kontaktanfrage erhalten - {{ salesChannel.name }}
        html: .shopware-cli/mail-template/contact_form/Deutsch-html.twig
        plain: .shopware-cli/mail-template/contact_form/Deutsch-plain.twig
        custom_fields: null
  - id: 67faf206afd841aa900226fff1610924
    translations:
      - language: English
        sender_name: '{{ salesChannel.name }}'
        subject: Contact form received - {{ salesChannel.name }}
        html: .shopware-cli/mail-template/contact_form/English-html.twig
        plain: .shopware-cli/mail-template/contact_form/English-plain.twig
        custom_fields: null
      - language: Deutsch
        sender_name: '{{ salesChannel.name }}'
        subject: Kontaktanfrage erhalten - {{ salesChannel.name }}
        html: .shopware-cli/mail-template/contact_form/Deutsch-html.twig
        plain: .shopware-cli/mail-template/contact_form/Deutsch-plain.twig
        custom_fields: null
```

there are two different contact_form templates with different id's. but they stored in same file path.

### Expected behaviour

```yaml
mail_template:
  - id: 554b74d5e6e940ac94728f6aafc99112
    translations:
      - language: English
        sender_name: '{{ salesChannel.name }}'
        subject: Contact form received - {{ salesChannel.name }}
        html: .shopware-cli/mail-template/contact_form/English-554b74d5e6e940ac94728f6aafc99112-html.twig
        plain: .shopware-cli/mail-template/contact_form/English-554b74d5e6e940ac94728f6aafc99112-plain.twig
        custom_fields: null
      - language: Deutsch
        sender_name: '{{ salesChannel.name }}'
        subject: Kontaktanfrage erhalten - {{ salesChannel.name }}
        html: .shopware-cli/mail-template/contact_form/Deutsch-554b74d5e6e940ac94728f6aafc99112-html.twig
        plain: .shopware-cli/mail-template/contact_form/Deutsch-554b74d5e6e940ac94728f6aafc99112-plain.twig
        custom_fields: null
  - id: 67faf206afd841aa900226fff1610924
    translations:
      - language: English
        sender_name: '{{ salesChannel.name }}'
        subject: Contact form received - {{ salesChannel.name }}
        html: .shopware-cli/mail-template/contact_form/English-67faf206afd841aa900226fff1610924-html.twig
        plain: .shopware-cli/mail-template/contact_form/English-67faf206afd841aa900226fff1610924-plain.twig
        custom_fields: null
      - language: Deutsch
        sender_name: '{{ salesChannel.name }}'
        subject: Kontaktanfrage erhalten - {{ salesChannel.name }}
        html: .shopware-cli/mail-template/contact_form/Deutsch-67faf206afd841aa900226fff1610924-html.twig
        plain: .shopware-cli/mail-template/contact_form/Deutsch-67faf206afd841aa900226fff1610924-plain.twig
        custom_fields: null
```
Maybe its the simplest solution, compose filename with id?

### Steps to Reproduce?

- duplicate **contact_form** email template and store other content in there
- run shopware-cli project config pull  
- there is only one export for **mail-template/contact_form**
