### ISSUE TITLE
Files without extension are not excluded in the 'extension zip' command

### ISSUE THREAD

**Issue by wannevancamp** [FriendsOfShopware/shopware-cli#370]
### Actual behaviour

shopware-extension.yml
```
build:
    zip:
        pack:
          excludes:
            paths:
              - .editorconfig
              - .php-cs-fixer.php
```

When the `.editorconfig` is available in the extension this file will not be ignored.

### Expected behaviour

`.editorconfig` should be excluded from the zip with it's configured in the exclude list.

### Steps to Reproduce?

1. Add `.editorconfig` to the extension root
2. Add `.editorconfig` to the zip exclude list in the shopware-extension.yaml
3. Run  `shopware-cli extension zip . `
4. File still exists in the zip
