### ISSUE TITLE
Zipping extensions fails when installing dart-sass

### ISSUE THREAD

**Issue by htuscher** [FriendsOfShopware/shopware-cli#85]
### Actual behaviour

I run `shopware-cli extension zip /path/to/extension --disable-git`

I get

```
INFO[0001] Downloading dart-sass                        
INFO[0001] Using dart-sass binary /root/.cache/dart-sass-embedded/dart-sass-embedded 
FATA[0001] close |0: file already closed      
```

### Expected behaviour

Build

### Steps to Reproduce?

See actual behavior

**Comment by shyim** [comment]
I guess you are using Alpine linux or?

**Comment by hhoechtl** [comment]
I'm using the platform-plugin-dev image.

```
build:pack-plugin:
  stage: build
  image:
    name: ghcr.io/friendsofshopware/platform-plugin-dev:v6.4.17
    entrypoint: [""]
  script:
    - ln -s "$(pwd)" "/plugins/${PLUGIN_NAME}"
    - echo $PLUGIN_NAME
    - pack-plugin "${PLUGIN_NAME}"
    - plugin-uploader ext:validate "$(realpath "${PLUGIN_NAME}.zip")"
  artifacts:
    paths:
      - "${PLUGIN_NAME}.zip"
    expire_in: 1 week
```

**Comment by shyim** [comment]
ahh yep it is alpine
https://github.com/FriendsOfShopware/platform-plugin-dev-docker/blob/master/Dockerfile.base#L2

see https://github.com/sass/dart-sass-embedded/issues/106 for the root problem

**Comment by hhoechtl** [comment]
Yes, I want to build storefront and admin js before zipping the plugin.
```
build:
  zip:
    composer:
      enabled: true
    assets:
      enabled: true
      enable_es_build_for_admin: true
      enable_es_build_for_storefront: true
```

**Comment by hhoechtl** [comment]
But then I have to download shopware on every build, don't I?

**Comment by shyim** [comment]
When you have enabled esbuild in both areas enabled it does not need Shopware files anymore. It compiles complete independent from it.

**Comment by hhoechtl** [comment]
You won't believe it, but this works:

Disabling the assets build in the `.shopware-extension.yml`:
```
build:
  zip:
    composer:
      enabled: true
    assets:
      enabled: false
      enable_es_build_for_admin: false
      enable_es_build_for_storefront: false
``` 

And building the extension first with `shopware-cli` and then executing zip:

```
build:pack-plugin:
  stage: build
  image:
    name: ghcr.io/friendsofshopware/platform-plugin-dev:v6.4.17
    entrypoint: [""]
  script:
    - jq '. += {"version":"'$CI_COMMIT_TAG'"} | del(."require-dev", ."repositories", ."autoload-dev", ."extra"."patches")' composer.json > composer.json
    - ln -s "$(pwd)" "/plugins/${PLUGIN_NAME}"
    - shopware-cli extension build "$(realpath /plugins/${PLUGIN_NAME})"
    - pack-plugin "${PLUGIN_NAME}"
    - plugin-uploader ext:validate "$(realpath "${PLUGIN_NAME}.zip")"
  artifacts:
    paths:
      - "${PLUGIN_NAME}.zip"
    expire_in: 1 week
```

**Comment by aragon999** [comment]
Maybe there is some confusion, regarding the two mechanisms how to build the assets. The one is using ES build, which builds independently from the Shopware JavaScript, and the other is more or less the standard Shopware build.

The `build` command always disables the ES Build option: https://github.com/FriendsOfShopware/shopware-cli/blob/main/cmd/extension/extension_build.go#L20 (not sure why @shyim or is the config just not implemented yet?).

It should work, if you use `pack-plugin "${PLUGIN_NAME}"` with the following config: 
```
build:
  zip:
    composer:
      enabled: true
```

Note that using this the assets are still built using the Shopware standard way: https://github.com/FriendsOfShopware/shopware-cli/blob/main/extension/asset_platform.go#L148-L163
