### ISSUE TITLE
ESBuild doesn't work if using core services

### ISSUE THREAD

**Issue by hhoechtl** [FriendsOfShopware/shopware-cli#86]
### Actual behaviour

If using services or classes from the Shopware core the compilation doesn't work.
According to the documentation e.g. `import Plugin from 'src/plugin-system/plugin.class';` already causes this error.

```
shopware-cli extension build custom/static-plugins/shopware-platform-delivery-time/

up to date, audited 2 packages in 5s

found 0 vulnerabilities
npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.1.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.1.2
npm notice Run npm install -g npm@9.1.2 to update!
npm notice 
INFO[0004] Downloading dart-sass                        
INFO[0005] Using dart-sass binary /root/.cache/dart-sass-embedded/dart-sass-embedded 

  extension.js   126.4kb
  extension.css   21.0kb

⚡ Done in 602ms
INFO[0005] Using dart-sass binary /root/.cache/dart-sass-embedded/dart-sass-embedded 
✘ [ERROR] Could not resolve "src/plugin-system/plugin.class"

    custom/static-plugins/shopware-platform-delivery-time/src/Resources/app/storefront/src/deliveryDate/deliveryDate.plugin.js:5:19:
      5 │ import Plugin from 'src/plugin-system/plugin.class';
        ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "src/plugin-system/plugin.class" as external to exclude it from the bundle,
  which will remove this error.

✘ [ERROR] Could not resolve "src/service/http-client.service"

    custom/static-plugins/shopware-platform-delivery-time/src/Resources/app/storefront/src/deliveryDate/deliveryDateTime.js:1:23:
      1 │ import HttpClient from 'src/service/http-client.service';
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "src/service/http-client.service" as external to exclude it from the bundle,
  which will remove this error.

2 errors
```

### Expected behaviour

It should compile

### Steps to Reproduce?

```yaml
build:
  zip:
    composer:
      enabled: true
    assets:
      enabled: false
      enable_es_build_for_admin: true
      enable_es_build_for_storefront: true
    pack:
      excludes:
        paths:
          - .cache
          - .editorconfig
          - .gitignore
          - .idea
```

```
docker run --rm -ti -v $PWD:/tmp/build -w /tmp/build --entrypoint= ghcr.io/friendsofshopware/shopware-cli:0.1.44 bash
shopware-cli extension build custom/static-plugins/shopware-platform-delivery-time/
```
